using System.ComponentModel.DataAnnotations;

namespace FinancialAppApi.Models;

public class AppUser
{
    [Key]
    public string Id { get; set; } = string.Empty;

    // While self-registration is closed after the first account, the initial user owns
    // slot 1. The nullable slot keeps the race-proof current behavior without making the
    // user table itself single-user: additional provisioned users can leave it null.
    public int? RegistrationSlot { get; set; }

    [Required]
    public string Username { get; set; } = string.Empty;

    [Required]
    public string NormalizedUsername { get; set; } = string.Empty;

    [Required]
    public string PasswordHash { get; set; } = string.Empty;

    public bool TotpEnabled { get; set; } = false;

    // DataProtection-encrypted TOTP secret, only set once TotpEnabled is confirmed.
    public string? TotpSecret { get; set; }

    // DataProtection-encrypted TOTP secret generated by /2fa/totp/setup but not yet confirmed
    // via /2fa/totp/enable. Kept separate from TotpSecret so an abandoned setup attempt can
    // never half-enable 2FA on the account.
    public string? PendingTotpSecret { get; set; }

    public int FailedLoginAttempts { get; set; } = 0;

    public DateTime? LockedUntil { get; set; }

    // Password checks used to unlock a session or reveal sensitive values have their own
    // lockout state. Keeping this separate prevents a typo in an already-authenticated
    // session from unexpectedly changing the normal login lockout counter.
    public int PasswordVerificationFailedAttempts { get; set; } = 0;

    public DateTime? PasswordVerificationLockedUntil { get; set; }

    public int TwoFactorFailedAttempts { get; set; } = 0;

    public DateTime? TwoFactorLockedUntil { get; set; }

    // Highest successfully consumed RFC 6238 time step. Persisting it makes a TOTP
    // code single-use even when two pending login tokens are submitted concurrently.
    public long? LastTotpTimeStep { get; set; }
}
