using System.ComponentModel.DataAnnotations;

namespace FinancialAppApi.Models;

public class AppUser
{
    [Key]
    public string Id { get; set; } = string.Empty;

    [Required]
    public string Username { get; set; } = string.Empty;

    [Required]
    public string PasswordHash { get; set; } = string.Empty;

    public string? Email { get; set; }

    public bool EmailVerified { get; set; } = false;

    public bool TotpEnabled { get; set; } = false;

    // DataProtection-encrypted TOTP secret, only set once TotpEnabled is confirmed.
    public string? TotpSecret { get; set; }

    // DataProtection-encrypted TOTP secret generated by /2fa/totp/setup but not yet confirmed
    // via /2fa/totp/enable. Kept separate from TotpSecret so an abandoned setup attempt can
    // never half-enable 2FA on the account.
    public string? PendingTotpSecret { get; set; }

    public int FailedLoginAttempts { get; set; } = 0;

    public DateTime? LockedUntil { get; set; }
}
