using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FinancialAppApi.Migrations
{
    /// <inheritdoc />
    public partial class AddAccountBalanceAdjustmentMarker : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "IsAccountBalanceAdjustment",
                table: "Transactions",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            // These rows were generated by account setup/balance correction paths before the
            // explicit marker existed. Keep their real balance effect, but remove them from the
            // Stability put-back lifecycle. The description predicates are migration-only legacy
            // backfill; runtime policy uses the durable marker instead of display text.
            migrationBuilder.Sql("""
                UPDATE "Transactions"
                SET "IsAccountBalanceAdjustment" = TRUE,
                    "StabilityReloadIntent" = 'NotRequired'
                WHERE "Id" LIKE '%-opening'
                   OR "Id" LIKE 'reconcile-%-adjustment%'
                   OR (
                        "Category" = 'Adjustment'
                        AND "AccountId" IS NOT NULL
                        AND (
                            "Description" LIKE 'Account balance alignment - %'
                            OR "Description" LIKE 'Balance Adjustment - %'
                            OR "Description" LIKE 'Balance Adjustment — %'
                        )
                   );
                """);

            // Account corrections change the current ledger and Stability replay inputs, so any
            // previously materialized cycle cache must be rebuilt from the updated transaction set.
            migrationBuilder.Sql("DELETE FROM \"CycleBalances\";");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "IsAccountBalanceAdjustment",
                table: "Transactions");
        }
    }
}
